const PDFDocument = require("pdfkit");

/**
 * @param {object} data
 * @returns {Promise<Buffer>}
 */
const buildPayslipPdf = (data) => {
  const {
    organizationName,
    employeeName,
    employeeEmail,
    payPeriod,
    basicSalary,
    hra,
    bonus,
    deductionAmount,
    grossTotal,
    netAmount,
    currency,
    status,
    notes,
  } = data;

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 48 });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).fillColor("#1e3a5f").text("PAYSLIP", { align: "center" });
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor("#64748b").text(organizationName || "Organization", { align: "center" });
    doc.moveDown(1.5);

    doc.fontSize(11).fillColor("#0f172a").text(`Employee: ${employeeName}`);
    doc.text(`Email: ${employeeEmail}`);
    doc.text(`Pay period: ${payPeriod}`);
    doc.text(`Status: ${status === "paid" ? "Paid" : "Unpaid"}`);
    doc.text(`Currency: ${currency || "INR"}`);
    doc.moveDown();

    const rows = [
      ["Basic salary", basicSalary],
      ["HRA", hra],
      ["Bonus", bonus],
      ["Gross earnings", grossTotal],
      ["Deductions", deductionAmount],
      ["Net pay", netAmount],
    ];

    doc.fontSize(10);
    rows.forEach(([label, val], i) => {
      const isNet = i === rows.length - 1;
      doc.fillColor(isNet ? "#047857" : "#334155").font(isNet ? "Helvetica-Bold" : "Helvetica");
      doc.text(`${label}: ${val}`, { continued: false });
    });

    if (notes) {
      doc.moveDown();
      doc.fillColor("#64748b").font("Helvetica").fontSize(9).text(`Notes: ${notes}`);
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor("#94a3b8").text("Generated by Staffly — This is a computer-generated document.", {
      align: "center",
    });

    doc.end();
  });
};

module.exports = { buildPayslipPdf };
